# -*- coding: utf-8 -*-
"""KKA_Tugas2_5025221102_MarcoMarcelloHugo.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TTzPu-CWYaaMevoqB-0RjJh2kZt7p3a_
"""

import heapq

# Graph dengan bobot edge
graph = {
    'S': {'A': 6, 'B': 5, 'C': 10},
    'A': {'S': 6, 'E': 6},
    'B': {'S': 5, 'E': 6, 'D': 7},
    'C': {'S': 10, 'D': 6},
    'D': {'C': 6, 'B': 7, 'F': 6},
    'E': {'A': 6, 'B': 6, 'F': 4},
    'F': {'E': 4, 'D': 6, 'G': 3},
    'G': {'F': 3}
}

# Heuristic (h)
heuristic = {
    'S': 17,
    'A': 10,
    'B': 13,
    'C': 4,
    'D': 2,
    'E': 4,
    'F': 1,
    'G': 0
}

def greedy_bfs(start, goal):
    visited = set()
    pq = []
    heapq.heappush(pq, (heuristic[start], start, [start], 0))  # (h(n), node, path, cost)

    while pq:
        h, node, path, cost = heapq.heappop(pq)

        if node in visited:
            continue
        visited.add(node)

        # Jika goal ditemukan
        if node == goal:
            return path, cost

        # Expand tetangga
        for neighbor, edge_cost in graph[node].items():
            if neighbor not in visited:
                heapq.heappush(
                    pq,
                    (heuristic[neighbor], neighbor, path + [neighbor], cost + edge_cost)
                )
    return None, float('inf')


# Jalankan
path, cost = greedy_bfs('S', 'G')
print("Jalur yang ditemukan dengan Greedy BFS :", path)
print("Total cost:", cost)